name: deployment

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Reason for manually triggering the build'
        required: true

  workflow_run:
    workflows:
      - build
    types:
      - completed
    branches: [ platform ]

jobs:
  temp:
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.workflow_run.head_branch }}  ${{github.event.workflow_run.conclusion}} "
