name: deployment

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Reason for manually triggering the build'
        required: true
  push:
    branches:
      - "platform"
      - "r[0-9][0-9].[0-9][0-9]"
    paths-ignore:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"
      - "!.github/workflows/gradle-build.yaml"
      - "infra/**"
      - "**/*.md"
      - ".gitignore"
  pull_request:
    branches:
      - "platform"
      - "r[0-9][0-9].[0-9][0-9]"
    paths-ignore:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"
      - "!.github/workflows/gradle-build.yaml"
      - "infra/**"
      - "**/*.md"
      - ".gitignore"

concurrency: build_${{ github.ref }}


jobs:
  temp:
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.workflow_run.head_branch }}  ${{github.event.workflow_run.conclusion}}"
  temp2:
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.workflow_run.head_branch }}  ${{github.event.workflow_run.conclusion}}"

